INSERT INTO hearing ( hearing_id, status, created_date_time, updated_date_time) VALUES ('2000000000', 'HEARING_REQUESTED', '2021-08-10 11:20:00','2021-08-12 13:30:00');
INSERT INTO hearing ( hearing_id, status) VALUES ('2000000011', 'HEARING_AMENDED');
INSERT INTO hearing ( hearing_id, status) VALUES ('2000000012', 'UPDATE_REQUESTED');
INSERT INTO hearing ( hearing_id, status) VALUES ('2000000013', 'AWAITING_LISTING');
INSERT INTO hearing ( hearing_id, status) VALUES ('2000000136', 'AWAITING_LISTING');
INSERT INTO hearing ( hearing_id, status) VALUES ('2000000100', 'LISTED');

insert into case_hearing_request (
  auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true, 'Some hearing type',	60,	'Priority type',	4,'f','f','AB123',null,'TEST'	,1111222233334444,	'2021-08-10 11:20:00','EXT/REF123',	'https://www.google.com',	'Internal case name','Public case name',	't'	,'CMLC123',	't',	'2021-10-10 00:00:00',	1,	2000000000	,'t'	,	'Some listing comments',	'Some judge',	'2021-11-01 00:00:00',	'2021-11-12 00:00:00');

insert into case_hearing_request (
 auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true, 'Some hearing type',	60,	'Priority type',	4,'f','f','AB123',null,'TEST'	,1111222233334444,	'2021-01-10 09:20:00','EXT/REF123',	'https://www.google.com',	'Internal case name','Public case name',	't'	,'CMLC123',	't',	'2021-02-10 00:00:00',	1,	2000000136	,'t'	,	'Some listing comments',	'Some judge',	'2021-03-01 00:00:00',	'2021-03-12 00:00:00');
insert into case_hearing_request (
 auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true, 'Some hearing type',	60,	'Priority type',	4,'f','f','AB123',null,'TEST'	,1111222233334444,	'2021-04-10 10:20:00','EXT/REF123',	'https://www.google.com',	'Internal case name','Public case name',	't'	,'CMLC123',	't',	'2021-05-10 00:00:00',	2,	2000000136	,'t'	,	'Some listing comments',	'Some judge',	'2021-08-01 00:00:00',	'2021-08-12 00:00:00');
insert into case_hearing_request (
 auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true,'Some hearing type',	60,	'Priority type',	4,'f','f','AB123',null,'TEST'	,1111222233334444,	'2021-08-10 11:20:00','EXT/REF123',	'https://www.google.com',	'Internal case name','Public case name',	't'	,'CMLC123',	't',	'2021-10-10 00:00:00',	3,	2000000136	,'t'	,	'Some listing comments',	'Some judge',	'2021-11-01 00:00:00',	'2021-11-12 00:00:00');


insert into case_hearing_request (
 auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true, 'Some hearing type2',	62,	'Priority type2',	5,'t','f','AB333',null,'XYZ1'	,1111222233335555,	'2020-08-10 11:20:00','EXT/REF783',	'https://www.google.com',	'Internal case name2','Public case name2',	'f'	,'CMLC333',	't',	'2020-10-10 00:00:00',	1,	2000000011	,'t'	,	'Some listing comments2',	'Some judge2',	'2021-11-01 00:00:00',	'2021-11-12 00:00:00');

insert into case_hearing_request (
  auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true, 'Some hearing type',	60,	'Priority type',	4,'f','f','AB123',null,'TEST'	,9856815055686759,	'2021-08-10 11:20:00','EXT/REF123',	'https://www.google.com',	'Internal case name','Public case name',	't'	,'CMLC123',	't',	'2021-10-10 00:00:00',	1,	2000000012	,'t',	'Some listing comments',	'Some judge',	'2021-11-01 00:00:00',	'2021-11-12 00:00:00');

insert into case_hearing_request (
  auto_list_flag, is_a_panel_flag, hearing_type, required_duration_in_minutes, hearing_priority_type, number_of_physical_attendees, hearing_in_welsh_flag, private_hearing_required_flag, lead_judge_contract_type, first_date_time_of_hearing_must_be, hmcts_service_code, case_reference, hearing_request_received_date_time, external_case_reference, case_url_context_path, hmcts_internal_case_name, public_case_name, additional_security_required_flag, owning_location_id, case_restricted_flag, case_sla_start_date, hearing_request_version, hearing_id, interpreter_booking_required_flag, listing_comments, requester, hearing_window_start_date_range, hearing_window_end_date_range)
VALUES ( 't'	, true,'Some hearing type',	60,	'Priority type',	4,'f','f','AB123',null,'TEST'	,1111222233334466,	'2021-08-10 11:20:00','EXT/REF123',	'https://www.google.com',	'Internal case name','Public case name',	't'	,'CMLC123',	't',	'2021-10-10 00:00:00',	1,	2000000013	,'t',	'Some listing comments',	'Some judge',	'2021-11-01 00:00:00',	'2021-11-12 00:00:00');
