java:
  applicationPort: 4561
  image: 'hmctspublic.azurecr.io/hmc/cft-hearing-service:latest'
  ingressHost: hmc-cft-hearing-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  autoscaling:
    enabled: false
  environment:
    CFT_HEARING_SERVICE_S2S_AUTHORISED_SERVICES: xui_webapp,hmc_hmi_inbound_adapter,sscs,fis_hmc_api
    CFT_HEARING_SERVICE_DB_OPTIONS: "?stringtype=unspecified&sslmode=require&gssEncMode=disable"
    HMC_SERVICE_BUS_TOPIC: hmc-to-cft-{{ .Values.global.environment }}
    HMC_SERVICE_BUS_SUBSCRIPTION: hmc-subs-to-cft-{{ .Values.global.environment }}
    HMC_SERVICE_BUS_QUEUE: hmc-from-hmi-{{ .Values.global.environment }}
    HMC_OUTBOUND_SERVICE_BUS_QUEUE: hmc-to-hmi-{{ .Values.global.environment }}
    IDAM_OIDC_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    HTTP_CLIENT_CONNECTION_TIMEOUT: '10000'
    HTTP_CLIENT_READ_TIMEOUT: '60000'
    HTTP_CLIENT_MAX_TOTAL: '200'
    HTTP_CLIENT_SECONDS_IDLE_CONNECTION: '120'
    HTTP_CLIENT_MAX_CLIENT_PER_ROUTE: '20'
    HTTP_CLIENT_VALIDATE_AFTER_INACTIVITY: '2000'
    CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    HMI_BASE_URL: https://hmi-apim.test.platform.hmcts.net/hmi
    HMI_SOURCE_SYSTEM: CFT
    HMI_DESTINATION_SYSTEM: SNL
    GRANT_TYPE: client_credentials
    FH_BASE_URL: https://login.microsoftonline.com

servicebus:
  enabled: false
